name: Accessibility

on:
  push:
  pull_request:

concurrency:
  group: accessibility-${{ github.ref }}
  cancel-in-progress: true

jobs:
  accessibility:
    name: Accessibility Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build
        env:
          NEXT_PUBLIC_BASE_URL: http://localhost:3000

      - name: Install axe and chrome
        run: |
          npm install -g @axe-core/cli
          npx browser-driver-manager install chrome

      - name: Extract sitemap URLs
        run: node scripts/extract-sitemap-url.mjs

      - name: Start Next.js app
        run: |
          pnpm run start &
          echo $! > .next_pid
        timeout-minutes: 2

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000

      - name: Run accessibility tests
        run: node scripts/run-a11y-tests.mjs

      - name: Kill Next.js server
        if: always()
        run: kill $(cat .next_pid)