name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Frontend build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Generate sitemap
        run: pnpm run generate:sitemap

      - name: Build project
        run: pnpm run build

  code_quality:
    name: Frontend code quality
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run biome
        run: biome ci